[phases.setup]
nixPkgs = ['python310','glibc']
aptPkgs = ["...", "wget",'ffmpeg','espeak','libavcodec-extra','libsm6','libxext6','libc6','libgl1-mesa-glx','libglib2.0-0','libsm6','libxext6','libxrender-dev','freeglut3-dev','libgtk2.0-dev','libgl1-mesa-glx','poppler-utils']
cmds = [
  'echo "Everything OK ----------------------------------"',
  'sudo apt-get install -y software-properties-common',
  "apt-get install -y build-essential libpng-dev libjpeg-dev libtiff-dev zlib1g-dev",
  "wget https://github.com/tesseract-ocr/tesseract/archive/refs/tags/5.3.4.tar.gz",
  "tar -xzf 5.3.4.tar.gz",
  "ls",
  "cd tesseract-5.3.4 && ./autogen.sh && ./configure && ./configure --prefix=/usr/local && make && sudo make install",
  'sudo apt-get -y update',
  'echo "Everything OK ----------------------------------"',
  'sudo apt-get install -y tesseract-ocr-eng',
  'sudo apt-get -y update',
  'ldd --version',
  'mkdir converted_images',
  'echo "Everything OK ----------------------------------"',
  'tesseract --version'
]


