[phases.setup]
nixPkgs = ['python310','glibc']
aptPkgs = ["...", "wget",'ffmpeg','espeak','libavcodec-extra','libsm6','libxext6','libc6','libgl1-mesa-glx','libglib2.0-0','libsm6','libxext6','libxrender-dev','freeglut3-dev','libgtk2.0-dev','libgl1-mesa-glx','libtesseract-dev','libtesseract5','poppler-utils','glibc-source']

cmds = [
  'nix-env -iA iconv -f https://github.com/NixOS/nixpkgs/archive/9957cd48326fe8dbd52fdc50dd2502307f188b0d.tar.gz',
  'sudo apt-get -y update',
  'sudo apt-get install -y software-properties-common',
  'sudo add-apt-repository -y --remove ppa:alex-p/tesseract-ocr',
  # 'sudo apt-get install -y --no-install-recommends ffmpeg espeak libavcodec-extra',
  # 'sudo apt-get install -y ffmpeg libsm6 libxext6 libc6 libgl1-mesa-glx libglib2.0-0 libsm6 libxext6 libxrender-dev',
  # 'sudo apt-get install -y freeglut3-dev libgtk2.0-dev libgl1-mesa-glx tesseract-ocr libtesseract-dev libtesseract5',
  'echo "Everything OK ----------------------------------"',
  'sudo apt-get install -y tesseract-ocr',
  # 'sudo apt-get install -y poppler-utils',
  # 'sudo apt-get install -y glibc-source',
  'sudo apt-get -y update',
  'mkdir converted_images',
  'echo "Everything OK ----------------------------------"',
  'tesseract --version']


