[phases.setup]
nixPkgs = ['python310','glibc']
aptPkgs = ["...", "wget",'ffmpeg','espeak','libavcodec-extra','libsm6','libxext6','libc6','libgl1-mesa-glx','libglib2.0-0','libsm6','libxext6','libxrender-dev','freeglut3-dev','libgtk2.0-dev','libgl1-mesa-glx','poppler-utils']

cmds = [
  # 'nix-env -iA iconv -f https://github.com/NixOS/nixpkgs/archive/9957cd48326fe8dbd52fdc50dd2502307f188b0d.tar.gz',
  'echo "Everything OK ----------------------------------"',
  'sudo apt-get install -y software-properties-common',
  "apt-get install -y build-essential libpng-dev libjpeg-dev libtiff-dev zlib1g-dev",
  "wget https://github.com/tesseract-ocr/tesseract/archive/refs/tags/5.3.4.tar.gz",
  "tar -xzf 5.3.4.tar.gz",
  "cd tesseract-5.3.4",
  "ls",
  "autogen.sh",
  "configure",
  "configure --prefix=/usr/local",
  "make",
  "sudo make install",
  
  # 'sudo add-apt-repository -y --remove ppa:alex-p/tesseract-ocr5',
  # "sudo add-apt-repository ppa:alex-p/tesseract-ocr-devel",
  'sudo apt-get -y update',
  'echo "Everything OK ----------------------------------"',
  # 'sudo apt-get install -y libtesseract-dev',
  # 'sudo apt-get install -y tesseract-ocr',
  'sudo apt-get install -y tesseract-ocr-eng',
  'sudo apt-get -y update',
  'ldd --version',
  # 'sudo apt-get install -y glibc-source',
  'mkdir converted_images',
  'echo "Everything OK ----------------------------------"',
  'tesseract --version']


