[phases.setup]
cmds = [
  'nix-env -iA iconv -f https://github.com/NixOS/nixpkgs/archive/9957cd48326fe8dbd52fdc50dd2502307f188b0d.tar.gz',
  'sudo apt-get update',
  'sudo apt-get install software-properties-common',
  'sudo add-apt-repository --remove ppa:alex-p/tesseract-ocr',
  'sudo apt-get install -y --no-install-recommends ffmpeg espeak libavcodec-extra',
  'sudo apt-get install -y ffmpeg libsm6 libxext6 libc6',
  'sudo apt-get install -y tesseract-ocr',
  'sudo apt-get install libtesseract-dev',
  'sudo apt-get install -y poppler-utils',
  'mkdir converted_images',
  'echo "Everything OK"',
  'tesseract --version']

nixPkgs = ['python310']
