[phases.setup]
aptPkgs = ["...", "wget"]
cmds = [
  'nix-env -iA iconv -f https://github.com/NixOS/nixpkgs/archive/9957cd48326fe8dbd52fdc50dd2502307f188b0d.tar.gz',
  'sudo apt-get -y update',
  'sudo apt-get install -y software-properties-common',
  'sudo add-apt-repository -y --remove ppa:alex-p/tesseract-ocr',
  'sudo apt-get install -y --no-install-recommends ffmpeg espeak libavcodec-extra',
  'sudo apt-get install -y ffmpeg libsm6 libxext6 libc6',
  'sudo apt-get install -y tesseract-ocr',
  'sudo apt-get install -y libtesseract-dev',
  'sudo apt-get install -y poppler-utils',
  'sudo apt-get install -y glibc-source',
  'mkdir converted_images',

  'echo "Everything OK ----------------------------------"',
  'mkdir $HOME/glibc/ && cd $HOME/glibc',
  'wget http://ftp.gnu.org/gnu/libc/glibc-2.32.tar.gz',
  'tar -xvzf glibc-2.32.tar.gz',
  'mkdir build',
  'mkdir glibc-2.32-install',
  'cd build',
  '~/glibc/glibc-2.32/configure --prefix=$HOME/glibc/glibc-2.32-install',
  'make',
  'make install',

  'echo "Everything OK ----------------------------------"',
  'tesseract --version']

nixPkgs = ['python310']
